main: com.thisisnzed.factionranking.launcher.Launcher
name: Ranking
author: Najtt
version: 1.1.0
database: true
depend: [Factions, Vault]
commands:
  classement:
    aliases: [ranking, factionranking, ftop, franking, point, points]