# _________                _____.__                            __  .__
# \_   ___ \  ____   _____/ ____\__| ____  __ ______________ _/  |_|__| ____   ____
# /    \  \/ /  _ \ /    \   __\|  |/ ___\|  |  \_  __ \__  \\   __\  |/  _ \ /    \
# \     \___(  <_> )   |  \  |  |  / /_/  >  |  /|  | \// __ \|  | |  (  <_> )   |  \
#  \______  /\____/|___|  /__|  |__\___  /|____/ |__|  (____  /__| |__|\____/|___|  /
#         \/            \/        /_____/                   \/                    \/

#SQL Database
host: "127.0.0.1"
port: 3306
database: "factionranking"
user: "mysql"
password: "password123"

#Commands
permission: "factionranking.admin"

#Leaderboard updater (in minute)
timeUpdater: 10

#GUI - Shared (FARM/PVP/GLOBAL)
topName: "&b&l%faction% &7&o(#%position%)"
topLore:
  - "&fPoints &l» &b&l%points%"

skullName: "&b&l%player%"
skullLore:
  - "&fArgent &l» &b%money%$"
  - "&fVotre faction &l» &b%faction%"
  - "&fPoints totaux &l» &b%points% point(s)"
  - "&fPosition globale &l» &b#%position%"

bestFactionsName: "&b&lTOP 10"
bestFactionsLoreByLine: "&b&l#%position% &7- &f%faction% &7&o(%points% points)"

#GUI - Ranking (FARM)
farmingTitle: "&b&lClassement &7- &fFactions"

#GUI - Ranking (PVP)
pvpTitle: "&b&lClassement &7- &fÉvènements"

#GUI - Ranking (GLOBAL)
globalTitle: "&b&lClassement &7- &fGlobal"

#GUI - Main
mainTitle: "&b&lClassement &7- &fChoix"
mainItemPvp: "&b&lClassement &7&o(PvP)"
mainItemFarm: "&b&lClassement &7&o(Farm)"
mainItemGlobal: "&b&lClassement &7&o(Global)"

mainItemPvpLore:
  - "&fLe classement &bpvp &fest basé sur les &bfactions"
  - "&fqui ont le plus de &bpoints &fdans les évènements &bPvP&f."
  - " "
  - "&fChaque évènement &bgagné &favec votre &bfaction"
  - "&fvous donnera des &bpoints &fafin que vous montiez"
  - "&fdans le &bclassement&f."

mainItemGlobalLore:
  - "&fLe classement &bglobal &fest basé sur les &bfactions"
  - "&fqui ont le plus de &bpoints &fdans les évènements &bPvP"
  - "&fmais aussi les &bfactions &fles plus &briches&f."
  - " "
  - "&fEn effet, ce classement &bglobal"
  - "&fadditionne les &bdeux &fclassements et donne"
  - "&fensuite les &bmeilleures factions &fdu serveur !"

mainItemFarmLore:
  - "&fLe classement &bfarm &fest basé sur les &bfactions"
  - "&fqui ont acheté le plus de &bpoints&f."
  - " "
  - "&fAchète toi aussi des &bpoints &fpour ta &bfaction"
  - "&fen tapant &b/boutique&f."